#!/bin/bash
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd $DIR
source ./shaddox.sh

task_vim() {
	log_util 'TASK' 'vim'
	install git
	install vim
	install curl
	ensure_mkdir ~/.vim
	ensure_ln_s ./vim/vimrc ~/.vimrc
	if [ ! -f ~/.vim/autoload/plug.vim ]; then
		log_info "Installing vim-plug"
		curl -fLs -o ~/.vim/autoload/plug.vim --create-dirs \
			    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
	fi
	log_info "Running PlugUpdate"
	vim +PlugUpdate +qall
}

task_zsh() {
	log_util 'TASK' 'zsh'
	install git
	install safe-rm
	install zsh
	ensure_ln_s ./zsh/zshrc ~/.zshrc
	ensure_ln_s ./zsh/zshrc.d ~/.zshrc.d
	if prompt_yn "Change shell to zsh?"; then
		log_info "Changing shell to zsh"
		chsh -s $(which zsh) || log_warn "'chsh -s $(which zsh)' failed, please do this manually"
	else
		log_info "Shell can be changed later by running 'chsh -s $(which zsh)'"
	fi
	if [ ! -f ~/.zsh-prompt-hide-host ]; then
		if prompt_yn "Show hostname in ZSH prompt?"; then
			log_info "Hostname can be hidden at any time by creating the file ~/.zsh-prompt-hide-host"
		else
			log_info "Creating file ~/.zsh-prompt-hide-host"
			touch ~/.zsh-prompt-hide-host
		fi
	fi
}

task_git() {
	log_util 'TASK' 'git'
	install git
	ensure_ln_s ./git/gitconfig ~/.gitconfig
	ensure_ln_s ./git/git-p4 /usr/lib/git-core/git-p4
}

task_tmux() {
	log_util 'TASK' 'tmux'
	install tmux
	ensure_mkdir ~/.tmux
	ensure_ln_s ./tmux/tmux.conf ~/.tmux.conf
}

task_gnupg() {
	log_util 'TASK' 'gnupg'
	install gpg
	ensure_mkdir ~/.gnupg
	ensure_ln_s ./gnupg/gpg.conf ~/.gnupg/gpg.conf
}

case "$1" in
	vim)
		task_vim
		;;
	zsh)
		task_zsh
		;;
	git)
		task_git
		;;
	tmux)
		task_tmux
		;;
	gnupg | gpg)
		task_gnupg
		;;
	'')
		task_vim
		task_zsh
		task_git
		task_tmux
		task_gnupg
		;;
	*)
		log_error "Unknown task '$1'"
		;;
esac
