#!/bin/bash
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd $DIR
source ./shaddox.sh

function task_vim {
	log_util 'TASK' 'vim'
	install git
	install vim
	ensure_ln_s ./vim/vimrc ~/.vimrc
	if [[ -e ~/.vim/bundle/Vundle.vim ]]; then
		log_info "updating Vundle"
		cd ~/.vim/bundle/Vundle.vim
		git pull
		cd $DIR
	else
		log_info "installing Vundle"
		ensure_mkdir ~/.vim/bundle
		git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
	fi
	vim +PluginInstall +qall
}

function task_zsh {
	log_util 'TASK' 'zsh'
	install git
	install zsh
	if [[ -e ~/.oh-my-zsh ]]; then
		log_info "updating oh-my-zsh"
		cd ~/.oh-my-zsh
		git pull
		cd $DIR
	else
		log_info "installing oh-my-zsh"
		git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
	fi
	ensure_ln_s ./zsh/zshrc ~/.zshrc
	ensure_ln_s ./zsh/minttyrc ~/.minttyrc
	ensure_ln_s ./zsh/nominaltech.zsh-theme ~/.oh-my-zsh/themes/nominaltech.zsh-theme
	ensure_ln_s ./zsh/nominaltech2.zsh-theme ~/.oh-my-zsh/themes/nominaltech2.zsh-theme
	chsh -s /bin/zsh || log_warn "could not chsh to zsh, please do this manually"
}

function task_git {
	log_util 'TASK' 'git'
	install git
	ensure_ln_s ./git/git-p4 /usr/lib/git-core/git-p4
	log_info "setting global git templatedir"
	git config --global init.templatedir '~/profile/git/template'
}

function task_tmux {
	log_util 'TASK' 'tmux'
	install tmux
	ensure_ln_s ./tmux/tmux.conf ~/.tmux.conf
}

case "$1" in
	vim)
		task_vim
		;;
	zsh)
		task_zsh
		;;
	git)
		task_git
		;;
	tmux)
		task_tmux
		;;
	'')
		task_vim
		task_zsh
		task_git
		;;
	*)
		log_error "unknown task '$1'"
		;;
esac
