#!/usr/bin/env sh

# Add ~/bin and ~/.local/bin to PATH
export PATH="$HOME/bin:$HOME/.local/bin:$PATH"

export TIME_STYLE=long-iso

export LSCOLORS="exfxcxdxbxegedabagacad"
export LS_COLORS="di=34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"

export BAT_PAGER="less -RFi"

# Set tab stop to 4 spaces
tabs -4

# Editor config
if [ -x "$(command -v nvim)" ]; then
	export EDITOR=nvim
	export VISUAL=nvim
	export GIT_EDITOR=nvim
	alias vim=nvim
else
	export EDITOR=vim
	export VISUAL=vim
	export GIT_EDITOR=vim
fi

# Load in the local profile if it exists.
if [ -f ~/.profile.local ]; then
	# shellcheck disable=SC1090
	. ~/.profile.local
fi
