#!/usr/bin/env ruby
require 'mustache'
defs = [:name, :author].reduce({}) { |o, k| 
	print "#{k}? "
	o[k] = gets.strip
	o 
}
['package.json'].each { |f| 
	File.write(f, Mustache.render(File.read(f), defs))
}
`npm install -d`
