# General
# ------------------------------------------------

setopt extended_glob
autoload -U colors && colors

# ZSH conf.d
# --------------------------------------------------

if [ -d $HOME/.zshrc.d ]; then
	for plugin in $HOME/.zshrc.d/*.zsh; do
		source $plugin
	done
fi

# Local Config
#--------------------------------------------------

if [ -e $HOME/.localrc ]; then
	source $HOME/.localrc
fi
