#!/usr/bin/env bash

# Standard convention to load the system bashrc
if [[ -f "/etc/bashrc" ]]; then
	source /etc/bashrc
fi

source ~/.profile
source ~/.common.sh

# ----------------------------------------------------------------------------
# Options

# Enable vi mode
set -o vi

# History
export HISTFILE="${HOME}/.bash-history"
shopt -s histappend
HISTCONTROL=ignoredups:erasedups
HISTSIZE=1000000
HISTFILESIZE=1000000

# Prompt
case "$TERM" in
	screen*)
		PROMPT_SCREEN='\[\ek\w\e\\\]'
		;;
	*)
		PROMPT_SCREEN=''
		;;
esac
case "$TERM" in
	xterm-color|*-256color)
		PROMPT="\[\e[90m\][\[\e[35m\]\u@\h\[\e[90m\]] \[\e[34m\]\w \[\e[90m\]$ \[\e[39m\]"
		;;
	*)
		PROMPT="[\u@\h] \w $ "
		;;
esac
export PS1="${PROMPT_SCREEN}${PROMPT}"

# ----------------------------------------------------------------------------
# Sourcing

# Enable FZF if installed
if [[ -f "${HOME}/.fzf.bash" ]]; then
	source "${HOME}/.fzf.bash"
fi
# FZF in nixos
if installed fzf-share; then
  source "$(fzf-share)/key-bindings.bash"
fi

if installed direnv; then
	eval "$(direnv hook bash)"
fi

# Local config
if [[ -f "${HOME}/.bashrc.local" ]]; then
	source "${HOME}/.bashrc.local"
fi
